###

GET http://localhost:8080/locations
Accept: application/json

###

GET http://localhost:8080/locations/1
Accept: application/json

###

POST http://localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
    "name": "Őr",
    "lat": 48.54791,
    "lon": 18.81674
}

###

PUT http://localhost:8080/locations/4
Content-Type: application/json
Accept: application/json

{
  "name": "Cserkeszőlő"
}

###

DELETE http://localhost:8080/locations/4

###

GET http://localhost:8080/locations
Accept: application/xml

###

GET http://localhost:8080/locations/1
Accept: application/xml

### Validation

POST http://localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
  "name": "Ajka",
  "lat": -147.54791,
  "lon": 219.81674
}

###

GET http://localhost:8080/hello
Accept: application/json

###
