###

GET http://localhost:8080/locations
Accept: application/json

###

GET http://localhost:8080/locations/1
Accept: application/json

###

POST http://localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
    "name": "Parasznya",
    "lat": 47.54791,
    "lon": 19.81674
}

###

PUT http://localhost:8080/locations/4
Content-Type: application/json
Accept: application/json

{
  "name": "Cserkeszőlő"
}

###

DELETE http://localhost:8080/locations/4