GET http://localhost:80/api/item?id=99
Accept: application/json

###

POST http://localhost:8080/api/movies
Content-Type: application/json

{
"title":  "Üvegtigris1"
}

###

GET http://localhost:8080/api/movies
Accept: application/json

###

POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title":  "Üvegtigris2"
}

###

POST http://localhost:8080/api/movies/2/rating
Content-Type: application/json

{
"rating": 4
}

###

POST http://localhost:8080/api/movies/1/rating
Content-Type: application/json

{
  "rating": 4
}

